### ISSUE TITLE
Switch from client-secret to certificate

### ISSUE THREAD

**Issue by ackbyte** [rayluo/identity#10]
Hi, I'm using the cool identity library successfully for Flask to perform the client-secret authentication.
Would like to switch from client-secret to certificate to increase the overall security of the application.
Any chance to use identity library with SSL-certificate?

Thanks!

**Comment by rayluo** [comment]
It is not yet officially documented, but currently as an implementation detail, the parameter `client_credential` accepts [all kinds of formats allowed by the underlying auth library](https://msal-python.readthedocs.io/en/latest/#msal.ClientApplication.params.client_id).

**Comment by ackbyte** [comment]
Thank you @rayluo! Here is a basic example of passing the parameters:

auth = identity.web.Auth(
    session=session,
    authority=app.config["AUTHORITY"],
    client_id=app.config["CLIENT_ID"],
    client_credential={"thumbprint": "abcdefghikdfdf12342323123", "private_key": open(config['private_key_file']).read()}
