### ISSUE TITLE
identity.web.Auth: get_token_for_user() returns error, despite tokens refreshed to latest

### ISSUE THREAD

**Issue by victorho-ty** [rayluo/identity#11]
Problem statement:
For our Flask App, we are not limiting web-sign-in session to 1 hour, but we are seeing get_token_for_user() returning error 1hr after user has logged in. Expectation is that as long as id/access tokens are refreshed (exp in tokens not yet expired(), get_token_for_user() would return valid session user.

What's found:
        user = self._get_user()
        if not user:  # Validate current session first
            return {"error": "interaction_required", "error_description": "Log in required"}

    def _get_user(self):
        id_token_claims = self._session.get(self._USER)
        return id_token_claims if id_token_claims is not None and _is_valid(id_token_claims) else None

In get_user(), it tries to validate the 'exp' of the session saved user. Even though the user has refreshed access/id token when accessing other protected API (i.e. token with exp to a later time than login time), this Flask session saved user id_claim still retains the exp (as of log_in time only), and hence this error will happen 1 hour after complete_login()

More history at: https://github.com/Azure-Samples/ms-identity-python-webapp/issues/121

Thanks!

**Comment by rayluo** [comment]
@victorho-ty , please run `pip install git+https://github.com/rayluo/identity.git@renew-session` to install a fix from its feature branch, and let me know how that works. Thanks.

**Comment by rayluo** [comment]
Shipped in [release 0.3.1](https://github.com/rayluo/identity/releases/tag/0.3.1)
