### ISSUE TITLE
Support for persistent credentials?

### ISSUE THREAD

**Issue by vsoraas** [rayluo/identity#12]
Hello!

Does this library support persistent credentials? My ideal workflow:

- User sign-in and consent
- Any other steps necessary to complete the auth flow
- Insert refresh_token (or equivalent; user_secret, etc.) in secure storage
- Pull user's refresh_token from secure storage to create credentials (and generate new access_token if necessary) without requiring new user auth

I can handle the secure storage manually, so my question is more scoped towards whether the library can construct credentials without requiring user sign-in every time.

**Comment by rayluo** [comment]
@vsoraas , please run `pip install git+https://github.com/rayluo/identity.git@renew-session` to install a fix from its feature branch, and let me know how that works. Thanks.

**Comment by rayluo** [comment]
Shipped in [release 0.3.1](https://github.com/rayluo/identity/releases/tag/0.3.1)
