### ISSUE TITLE
After authentication, identity returns "Reverse for 'index' not found."

### ISSUE THREAD

**Issue by Trevato** [rayluo/identity#18]
Error points to this line:

https://github.com/rayluo/identity/blob/bffaa755b21365e1e5473bfc223647d74c70cbac/identity/django.py#L224

The project I'm working on doesn't have an index and the `auth_response()` function is hardcoded to redirect to it. I could hack it together to work for this project, but I don't want my solution to be immediately deprecated. Will the TODO be addressed soon?

**Comment by rayluo** [comment]
> Will the TODO be addressed soon?

Yes. You will receive notification when we close this. Stay tuned.

Meanwhile, you may consider adding a dummy index page for your project. This workaround can at least unblock you.

**Comment by rayluo** [comment]
It turns out there is an easy fix. Please [try this one](https://test.pypi.org/project/identity/0.5.2a1/) and report back the result, @Trevato 

`pip install -i https://test.pypi.org/simple/ identity==0.5.2a1`

If it goes well, a new release will be shipped soon.

**Comment by vespo92** [comment]
Tagging @Trevato  for transparency. 

identity==0.5.2a1 worked out of the box without the dummy index page. 

I did try the identity==0.5.1 that you pushed today on the latest version. That was still providing the same error as above.

We will use identity==0.5.2a1 in the interim.

**Comment by rayluo** [comment]
Thanks for your confirmation. A new [version `0.5.2` version](https://pypi.org/project/identity/) is shipped just now.
