### ISSUE TITLE
Fetching App Roles for the logged in user?

### ISSUE THREAD

**Issue by howardjones** [rayluo/identity#2]
I have a user who is a member of groups that have an App Role that is defined for my web app. 

In my callback view, I am fetching an azure token to be able to call the graph API:

    auth.get_token_for_user(["User.ReadBasic.All"])['access_token']

but if I use that token to call 

    https://graph.microsoft.com/v1.0/users/{user_id}/appRoleAssignments?$filter=resourceId+eq+{app_object_id}
    
I always get an empty list.

Is this expected? What is the right way to handle this?

**Comment by rayluo** [comment]
This library successfully obtained a token for you. So there is not much we can do here.

I can see you already read the [App Roles document](https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-add-app-roles-in-azure-ad-apps) and created a question to ask [how to receive the app roles from a token](https://github.com/MicrosoftDocs/azure-docs/issues/106694). Let's wait for an answer there.

After you make adjustments to let AAD issue the `roles` claim, you can troubleshoot by pasting the token into https://jwt.ms

**Comment by howardjones** [comment]
Just to close the loop on this: if you assign App Roles to a User or a Group, you get the `roles:` claim in your token, as expected. However they are *not* inherited by groups that are members of that group (nested), only direct members.

**Comment by rayluo** [comment]
Thanks for sharing this back to the community! Good to know. Guess this means the roles-based authorization would need to take this into consideration. :-/
