### ISSUE TITLE
Provide a way to override the login template

### ISSUE THREAD

**Issue by pamelafox** [rayluo/identity#23]
Developers would like it to match their look & feel

**Comment by rayluo** [comment]
Such a need was foreseen.

You can customize it by copying https://github.com/rayluo/identity/blob/dev/identity/templates/identity/login.html and save it into `your_project_root/templates/identity/login.html` and then start customizing it.

This solution works for the current 2 frameworks that are supported: Flask and Django. I plan to add the instruction into the template itself as a hint.

**Comment by pamelafox** [comment]
That works for my Quart branch as well, thanks! So my request is now just to document it.
