### ISSUE TITLE
Session object for Auth class

### ISSUE THREAD

**Issue by r3r00t3d** [rayluo/identity#3]
Hi,

first of all, thanks for the library. I'm having issue with the `Auth` class in `identity.web package`. The `session` object, that is one of the parameters, is described as what you can pass to it, but doesn't explicitly say what keys are actually required. The reason why I'm asking is because I'm using Tornado, and it would be really helpful to have more info than "if you're using Flask pass x and if you're using Django pass y".

Thanks again for the effort.

**Comment by rayluo** [comment]
[The session parameter is documented as a dict-like object](https://identity-library.readthedocs.io/en/latest/#identity.web.Auth.params.session). It does not "require" any keys to be preexist. The `Auth` object will maintain several key-value pairs it needs.

Currently, we mentioned Flask's session and Django's session, only because they are popular web frameworks in Python. But any other dict-like object in other web framework should work.

Tornado does not seem to provide a session API out-of-box. But perhaps you can somehow wrap its `RequestHandler.get_secure_cookie()` into a dict-like helper, and feed it into `identity.web`'s `Auth`. Let us know how that goes. :-)

**Comment by r3r00t3d** [comment]
Thanks for the answer. I'm still having issues on what interface should be implemented as I can just inherit a Dictionary but apparently I cannot just give the dict or dict-like object (I tried that and I get an error like "Invalid grant - state missing from auth_code_flow"). From your source code, I can see that you're using the following keys in the dictonary:

``` 
_TOKEN_CACHE = "_token_cache"
_AUTH_FLOW = "_auth_flow"
_USER = "_logged_in_user"
```

which probably means that I need to provide those three values in that dictionary in order for session object to be correct or maybe I'm misinterpreting something?

Sorry again for the hassle...

**Comment by rayluo** [comment]
This library will write and subsequently maintain its data using those keys. But that is an implementation detail. You as the caller do not need to "provide those three values". In fact, you won't know what value to be put in. All you need is to provide a dict-like interface. Now, "dict-like" means both get and set. Does your dict-like object actually implement the `__setitem__()` to properly write the data back? FWIW, there seems to be some existing Tornado session implementations out there on PyPI. You may have an easier time to use an off-the-shelf session.

**Comment by r3r00t3d** [comment]
Understood. I guess I'll need to do my part of implementing session management myself or using 3rd party prior to using Auth object. 

Thanks again.

**Comment by rayluo** [comment]
You are welcome. Please reply back and share your session solution. We can then mention it inside our docs to help future Tornado users.

**Comment by r3r00t3d** [comment]
So I've created custom session handler largely inspired by https://gist.github.com/viyatb/9641999 (there needed to be some changes). My code is still bad, but I'm planning to clean it up and at least put a gist online, but the aforementioned gist is 90% correct for general use case. I'm using `RequestHandler.set_secure_cookie()` as a means of creating session id and then creating a session object that persists in the database during the session. 

The only missing part for me is when I call `complete_log_in` method. I get an error response `state mismatch: <random string> vs None`. When I look at the signature of the method `log_in` I see that a `state` parameter is optional, and I guess , as I do want to use it in a redirect_uri mode, that I need to set it up to some value as I see that there is a state defined as a random string in an `auth_uri` that is returned. 

The question is what should that `state` hold and do I need to reuse that state anywehere else?


Thanks.

**Comment by rayluo** [comment]
That [`state` parameter is defined in the documentation as optional](https://identity-library.readthedocs.io/en/latest/#identity.web.Auth.log_in.params.state), so, `Auth` class will automatically generate a random one and stick to it, or `Auth` will accept whatever input from you and still stick to it. In either case, you are not supposed to run into a "state mismatch" error. Now that you did run into that error, I believe your question of "what should that state hold" is irrelevant.

Can you double check your still-in-development homebrew session module first? Unit test it to make sure it does persist data?

**Comment by r3r00t3d** [comment]
That might be connected to the issue of Tornado being multithreaded async and not having a global store (I mean it has, but it's application wide). I need to keep Auth object persistent for the session for multiple tenants (clients) and one of the options is keeping it in the database. 

However, I see that you're using caches (which might complicate things if they are continuously updated)for requests so my question is: is it possible to serialize and store Auth object and every time I need it deserialize it and use it for e.g log in and log out? Or is it mandatory for Auth object to reside in memory all the time?

**Comment by rayluo** [comment]
Even if you could serialize the Auth object, where would you put it? A centralized database? Then why don't you just implement the session into your database (and your probably should), and everything should just work out of the box? From the very beginning, Auth object's document tells you to provide a session which, by definition, should be something that persists across different requests. I think the direction to go is to find or build a session mechanism for Tornado, and then plug it into Auth. We can go from there.
