### ISSUE TITLE
Flask-Sessions versioning

### ISSUE THREAD

**Issue by ajstewart** [rayluo/identity#34]
Not an issue as such but I was wondering if there is a reason why Flask-Sessions is limited to `<0.6`?

Some later features (like the `flask session_cleanup`) that I went to use made me realise that this library limits it to v0.5.

**Comment by rayluo** [comment]
There was no particular reason. It was just a setup that was backported from earlier prototypes. At that time, the latest Flask-session was in 0.5.x.

After glancing through [Flask-session's recent changelog](https://flask-session.readthedocs.io/en/latest/changes.html), their removed APIs do not seem to be used by us. So, I believe you can force install a Flask-session 0.8. Please let us know how that goes. I'll probably also test it later when I get some time.
