### ISSUE TITLE
How to get Refresh Token with this library

### ISSUE THREAD

**Issue by murtv** [rayluo/identity#43]
I need to perform the Authorization Code Flow to get the access and refresh tokens so I can make API calls. But I don't want to secure any endpoints, therefore `@auth.login_required` seems to be **not** what I need.

I tried using `auth.log_in` with `auth.complete_log_in` and `auth.get_token_for_user`, but I don't get the refresh token this way.

Is it possible to get the refresh token with this library. Furthermore, is this library suitable for performing Authorization Code Flow not for signing users into own application but only to call microsoft APIs?

Code I'm using:
```
   values = auth.log_in(
        scopes=MICROSOFT_SCOPES,
        redirect_uri=flask.url_for("oauth2_callback_microsoft", _external=True),
        prompt="consent",
        )
    auth_uri = values["auth_uri"]
    return flask.redirect(auth_uri)
```

```
    result = auth.complete_log_in(request.args)
    if "error" in result:
        print(result)
    token_result = auth.get_token_for_user(MICROSOFT_SCOPES)
    print(token_result)
```
I don't get the refresh token here.

**Comment by rayluo** [comment]
This library does get Refresh Token (RT) under the hood, and *automatically* utilize it to refresh your access token (AT) when needed. You do not need to do anything extra to get that; just keep calling its API(s) to get an AT and you are good. So, this answers your original question.

P.S.: I have an unrelated question here is that you said "But I don't want to secure any endpoints". What kind of app are you building? A website? Or a desktop app/script? This library is (currently) geared towards web apps. If you are not building a web app at all, and instead is building a desktop script (for example, something like Microsoft's Azure CLI), you may consider using `identity` library's upstream dependency, [Microsoft's MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-python).

**Comment by murtv** [comment]
Thanks for the response.

I am building a web app but I'm not trying to secure my app with Microsoft Sign In. The refresh token is for building a "Connect Outlook Mail" feature. Since I'm doing the same with Google, I'd like to do that here too. 

I think MSAL seems the answer here.

**Comment by rayluo** [comment]
> I am building a web app but I'm not trying to secure my app with Microsoft Sign In. The refresh token is for building a "Connect Outlook Mail" feature.

If I understand it correctly, your web app would still (1) require the users to sign in initially to establish their existence (such as their RT) in your app, and then (2) your app will use some background workers to periodically fetch the users' email.

This `identity` library is still a better choice than MSAL for `#1`, but I'll need to figure out a way to do `#2`, maybe in a new sample when I get around to it.

**Comment by murtv** [comment]
Yes, you have it right. 

> This identity library is still a better choice than MSAL for #1

I'm storing the RT in the database for Google Gmail. When using this library would I store the access token?

**Comment by rayluo** [comment]
The `context` returned by the `@auth.login_required(..., scopes=[...])` will contain a refresh token, providing that the Identity Provider did issue one. So, that one can unblock you for now.

I'm still thinking of a better pattern to do this. I will update this thread when I come up with something.

**Comment by murtv** [comment]
Thanks Ray. You were very helpful. I will try this approach and report back.

**Comment by murtv** [comment]
Hi Ray, I am able to get the refresh token this way but there is still an issue: the refresh token is `None` after the first login. With Google, we set `prompt=consent&access_type=offline` which got us a RT every time (we wanted the consent screen anyways.) I looked at the docs for this library but I don't see a way to pass params in the authorization uri.

**Comment by murtv** [comment]
Because of this specific set of requirements I think I will need something lower level so I'm closing this issue now. Thanks for your time.
