### ISSUE TITLE
Alternate path for login.html template

### ISSUE THREAD

**Issue by 1jamesthompson1** [rayluo/identity#44]
I have been using this package with the identity.web.Auth for a little while. I wanted to swtich over to using the login_required decorator and flask.Auth (as it is a flask app). 

This means however that it uses the template at `project_root/templates/identity/login.html` where my webapp is actually within another project and so in a sub folder. Therefore it looksl ike  `project_root/webapp/templates/identity/login.html`. Is there a way to update the template path to point to this?

My current app can be found here: https://github.com/1jamesthompson1/TAIC-report-summary/blob/main/viewer/app.py

**Comment by rayluo** [comment]
Thanks for your interest. Upgrading to latest version with higher level API (the login_required decorator) is definitely the recommended direction.

> however that it uses the template at `project_root/templates/identity/login.html` where my webapp is actually within another project and so in a sub folder. Therefore it looksl ike `project_root/webapp/templates/identity/login.html`. Is there a way to update the template path to point to this?

I haven't tried this "webapp inside a sub folder" setup before. Did you actually try it? And if so, what template path does `identity` use, `project_root/templates/identity/login.html` or `project_root/webapp/templates/identity/login.html`?

Also, the recent versions of `identity` came with a built-in login.html which typically acts as an auto redirect, so you don't have to customize it at all. Can `identity` still locate its default login.html (i.e. does the login feature still work by default in your setup), assuming we don't need customization (for the sake of discussion)?

Last but not least, in Flask world, a stand-alone component is likely to be organized as a Blueprint, which can have its own templates etc., so, that might be something you can look into. Admittedly, I haven't given it much thought on how `identity` is used inside a Blueprint. Auth is usually a global topic.

**Comment by 1jamesthompson1** [comment]
Thanks for your response

You are right it does with the login template if you put it in `project_root/webapp/templates/identity/login.html`. I must of made a mistake before when testing it.
