### ISSUE TITLE
Different login process after using @auth.login_required decorator

### ISSUE THREAD

**Issue by 1jamesthompson1** [rayluo/identity#45]
_I should preface this that I am not overly familiar with either Flask or MSAL/Azure authentication_

From #44 I have somewhat got my app working with the login decorator. However the login process is not the same as it was before. It is using a code to login and after going through mulitple microsoft and a successful login page it does not return back to the webapp.

The previous login process had no code and had less screens of logging in with. See my previous code that just uses the web and works with this workflow

https://github.com/1jamesthompson1/TAIC-report-summary/blob/b1920d2207625775d7e746699ac7e153262621a9/viewer/app.py#L46-L51
and 
https://github.com/1jamesthompson1/TAIC-report-summary/blob/b1920d2207625775d7e746699ac7e153262621a9/viewer/app.py#L120-L163

My question would be how do I get the same login experience while using the @login_decorator?

**Comment by rayluo** [comment]
> the login process is not the same as it was before. It is using a code to login and after going through mulitple microsoft and a successful login page it does not return back to the webapp.

Sounds like you did not feed the redirect_uri parameter into the `identity` library. Please refer to [the doc](https://identity-library.readthedocs.io/en/latest/flask.html) here.

**Comment by 1jamesthompson1** [comment]
Ah yes, I had missed that when switching over from .web to .flask.

I am now looking at updating my testing.

Currently my tests look like this:
https://github.com/1jamesthompson1/TAIC-report-summary/blob/swtich-to-identity-flask/tests/test_app.py

With a mock auth object like so:
https://github.com/1jamesthompson1/TAIC-report-summary/blob/12043b71dade588698a2d8bc04a48b8fa0aa2a34/tests/test_app.py#L11C1-L21C16

What do I need to change to make it work with identity.flask?
I assume I am going to mock the login_required function something like this:
```python
@pytest.fixture
def client():
    # Mock the Auth class
    with patch("viewer.app.auth") as MockAuth:
        mock_auth = MagicMock()
        mock_auth.get_user.return_value = {"id": "test_user", "name": "Test User"}
        
        # Mock the login_required decorator to inject a context with a user
        def mock_login_required(f):
            def decorated_function(*args, **kwargs):
                context = {"user": mock_auth.get_user()}
                return f(*args, context=context, **kwargs)
            return decorated_function
        
        mock_auth.login_required = mock_login_required
        
        # Apply the mock
        MockAuth.return_value = mock_auth
        app.auth = mock_auth
        
        with app.app.test_client() as c:
            yield c 

I have tried this and it doesnt seem to work to get past the `login_required` decorator.


Lastly for the redirect_uri is there a way to make it truly dynamic so I dont have to set it as a environment variables?
```

**Comment by rayluo** [comment]
> I am now looking at updating my testing.
> 
> Currently my tests look like this: ...
> 
> What do I need to change to make it work with identity.flask? I assume I am going to mock the login_required function something like this:

I haven't looked into your code snippet yet. But perhaps you can first see whether [the test case inside this library's code base](https://github.com/rayluo/identity/blob/dev/tests/test_flask.py#L46) works for you?


> Lastly for the redirect_uri is there a way to make it truly dynamic so I dont have to set it as a environment variables?

What do you mean? The `redirect_uri` is just parameter for the `Auth` object, so, you can use whatever way you prefer to supply it: env var, configure file, hardcoded, etc..

In practice, `redirect_uri` is determined by the app's registration, so, it is considered as a constant for a given app (thus you could hard code it if you are developing one specific app); and if you are developing a library, you would want to expose it as your input parameter.

**Comment by 1jamesthompson1** [comment]
WIth regard to the `redirect_uri` I was hoping for a way to get the root URL before initiating the Auth object. But I think it can only be done with the request context therefore I asumme setting it in config / env is the way it has to be done.

I have tried the tests from the library and they seem to be working for me.

Ideally I was hoping that I could easily Mock the Auth class to keep my test file as close to its current state.

**Comment by rayluo** [comment]
> WIth regard to the `redirect_uri` I was hoping for a way to get the root URL before initiating the Auth object. But I think it can only be done with the request context therefore I asumme setting it in config / env is the way it has to be done.

The real reason is NOT because the root URL (i.e. the domain) could only be detected with the request; it is because (1) a web app deployed behind a proxy cannot always detect its domain; (2) this library actually supports the "different login process" that you found when redirect_uri is not configured (and that is a feature, not a bug <sup>TM</sup>). So, the current API design automatically guides you to the right programming model.
