### ISSUE TITLE
New user login does not ask for a password, if another user is already logged in.

### ISSUE THREAD

**Issue by qburst-sachinwhiteman** [rayluo/identity#7]
Hi, 
I'm using Identity package to integrate Azure AD authentication.
If one user is already logged in and another user tries to login from the same browser, 
complete_log_in method returns old user credentials.

**Comment by rayluo** [comment]
Indeed, currently the already logged in user would need to sign out first.

We will add a new change to allow the app to opt for showing login UI. You will receive notification from this issue once we make some changes.

**Comment by qburst-sachinwhiteman** [comment]
Is there any particular way in MSAL package that i can use to handle this issue?
Any help is appreciated

**Comment by rayluo** [comment]
Actually you can try `pip install git+https://github.com/rayluo/identity` and then in your web app you will be able to do
```python
...
auth.log_in(
    scopes=["YOUR_SCOPE"],
    redirect_uri="https://example.com/your/redirect/uri",
    prompt="select_account"  # <-- This line will do the trick
)
```

Test it and let us know how that goes. If it works, we will ship a new version soon.

**Comment by qburst-sachinwhiteman** [comment]
thanks @rayluo , 
will check and update it.

**Comment by qburst-sachinwhiteman** [comment]
@rayluo this one partially solves my issue with prompt="login", could you roll out this as a new version.

**Comment by qburst-khalid** [comment]
@rayluo 
Any Update on this ?. Thanks in advance.
```
If one user is already logged in and another user tries to login from the same browser, complete_log_in method returns old user credentials.

-----------------
Indeed, currently the already logged in user would need to sign out first.

We will add a new change to allow the app to opt for showing login UI. You will receive notification from this issue once we make some changes.
```
